name: Checkout with actions
on: [push]

jobs:
  checkout-and-display-files:
    runs-on: ubuntu-latest
    steps:
      - name: List dir before checkout
        run: ls -la

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: List dir after checkout
        run: ls -la