name: Docker
on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    container: 
      image: node:21-alpine3.18
    #   credentials:
    #     username: username
    #     password: password
      env:
        API_URL: example.com
      ports:
        - 80
    #   volumes:
    #     - my_docker_volume:/volume_mount
    #     - /data/my_data
    #     - /source/directory:/destination/directory
    #   options: --entrypoint /bin/sh --cpus 1
    steps:
      - name: Show node and OS versions
        run: |
          node -v
          cat /etc/os-release
      - name: Show API_URL env
        run: echo $API_URL
      - name: Show node version
        uses: docker://node:20.9.0-alpine3.18
        with:
          arg: '-v'
    #   - name: Container step 1
    #     uses: docker://node:20.9.0-alpine3.18
    #     with:
    #       entrypoint: /bin/sh
    #       args:
    #         -c 
    #         - node
    #         - p
    #         - 2+5
      - name: Container step 2
        if: ${{ always() }}
        uses: docker://node:20.9.0-alpine3.18
        with:
          entrypoint: /bin/sh
          args: '-c "node -p 2+5"'
    #   - name: Container step 3
    #     if: ${{ always() }}
    #     uses: docker://node:20.9.0-alpine3.18
    #     with:
    #       entrypoint: /bin/sh
    #       args: [-c, node, -p, 2+5]