name: Repository Events
on:
  push:
    branches:
      - main
      - 'feature/**'
      - '!feature/exclude-me'
    # You cannot use branches and branches-ignore for the same event in a workflow
    # branches-ignore:
    #   - ignore-me
    tags:
      - v1.*
      - '!v0'
    paths:
      - '**.js'
      - '!docs/**'
  pull_request:
    branches:
      - main
    paths:
      - '**.js'
  issues:
    types: 
      - opened
      - edited

jobs:
  checkout-test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11