name: Extensions and contexts
on:
  - push
  - pull_request
  - issues
  - workflow_dispatch
run-name: "Extensions and contexts build #${{ github.run_number }} triggered by ${{ github.actor }}, event: ${{ github.event_name}}"
jobs:
  exp-and-ctx:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Expressions
        id: expressions
        run: |
          echo ${{ 1 }}
          echo ${{ 'Simple string' }}
          echo ${{ null }}
          echo ${{ true }}
          echo ${{ 1 > 2 }}
          echo ${{ 'string' == 'String' }}
          echo ${{ true && false }}
          echo ${{ true || (true && false) }}

      - name: Dump contexts
        run: |
          echo '${{ toJson(github) }}'
          echo '${{ toJson(job) }}'
          echo '${{ toJson(secrets) }}'
          echo '${{ toJson(steps) }}'
          echo '${{ toJson(runner) }}'

      - name: Output Run ID
        run: echo ${{ github.run_id }}
      - name: Output Run Number
        run: echo ${{ github.run_number }}
      - name: Output Run Attempt
        run: echo ${{ github.run_attempt }}
    # This is how we can show secret data
    #   - name: Write and read file
    #     run: |
    #       echo '${{ toJson(secrets) }}' | sed -e 's/\(.\)/\1\n/g' 
