name: External events
on:
  repository_dispatch:
    types: [on-demand-test]

jobs:
  test-repo-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Simple echo
        run: echo "${{ github.event_name }}"
      - name: Echo var from client payload
        run: |
          echo "${{ github.event.client_payload }}"
          echo "----------------------------------"
          echo "${{ github.event.client_payload.unit }}"
          echo "${{ github.event.client_payload.integration }}"
