name: Build and publish docker image
on:
  push:
#   release:
#     types: [published]

jobs:
  push-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Clone src code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          repository: github-actions-course/node-js-api
          ref: 69f4a069f02bbced7d0b2f9f25b79a462d4cfe32
      - run: ls -la
    #   - name: Extract metadata
    #     id: metadata
    #     uses: docker/metadata-action@f3c3cad8ad5e1076ffba2449385b1547f1e3c566
    #     with:
    #       images: |
    #         hryshchenkoihor/simple-node-api
    #         ghcr.io/${{github.repository}}
    #       tags: |
    #         type=semver,pattern={{version}}
    #         type=semver,pattern={{major}}.{{minor}}
    #   - name: Login to Dockerhub
    #     uses: docker/login-action@3d58c274f17dffee475a5520cbe67f0a882c4dbb
    #     with:
    #       registry: ghcr.io
    #       username: ${{ github.actor }}
    #       password: ${{ github.token }}
    #   - name: login to GHCR
    #     uses: docker/login-action@3d58c274f17dffee475a5520cbe67f0a882c4dbb
    #     with:
    #       username: ${{ secrets.DOCKER_USERNAME }}
    #       password: ${{ secrets.DOCKER_PASSWORD }}
    #   - name: Build and push
    #     uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56
    #     with:
    #     #   context: https://github.com/github-actions-course/node-js-api.git#69f4a069f02bbced7d0b2f9f25b79a462d4cfe32
    #       file: node-js-api-workflows/Dockerfile
    #       push: true
    #       tags: ${{ steps.metadata.outputs.tags }}
    #       labels: ${{ steps.metadata.outputs.labels }}
            
        