name: Reusable workflow
on:
  workflow_call:
    inputs:
      name:
        description: "Input description"
        type: string
        default: Ihor
        required: false
    secrets:
      access-token:
        description: "Secret descriprion"
        required: true
    outputs:
      date:
        description: "Date value"
        value: ${{ jobs.generate-optputs.outputs.reusable-date }}

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Simple ls
        run: ls -laR

  log-context-and-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Show Github context
        run: echo "${{ toJson(github) }}"
      - name: Show input
        run: echo "${{ inputs.name }}"
      - name: Show secret
        run: echo "${{ secrets.access-token }}"

  generate-optputs:
    runs-on: ubuntu-latest
    outputs:
      reusable-date: ${{ steps.simple-output.outputs.date }}
    steps:
      - name: Add outputs
        id: simple-output
        run: echo "date=$(date)" >> $GITHUB_OUTPUT