name: Test API
on: [push, workflow_dispatch]

jobs:
  test-api:
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    services:
      app:
        image: alialaa17/simple-node-api:1.0
        # ports:
        #   - 3001:3000
        env:
          MONGO_HOSTNAME: mongo

      mongo:
        image: mongo
        # ports:
        #   - 27017:27017

    steps:
    #   - name: Clone src code
    #     uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    #     with:
    #       repository: github-actions-course/node-js-api
    #       ref: 69f4a069f02bbced7d0b2f9f25b79a462d4cfe32
      - name: Install curl
        run: |
          apt-get -y update
          apt-get -y install curl
      - name: Dump services context 
        run: echo '${{ toJson(job.services) }}'
      - name: Post a user
        run: 'curl -X POST http://app:3000/api/users -H ''Content-Type: application/json'' -d ''{"username": "hello","address": "Ihor"}'''
      - name: Get list of users
        run: curl 'http://app:3000/api/users'