name: Calling reusable workflow
on:
  workflow_dispatch:
    inputs:
        name:
          description: "Input description"
          type: string
          default: "Ihor"
          required: false

jobs:
  compare-token:
    runs-on: ubuntu-latest
    steps:
      - name: Compare github tokens
        run: "[[ '${{ github.token }}' == '${{ secrets.GITHUB_TOKEN }}' ]] && echo 1 || echo 2"

  calling-reusable-wf:
    uses: ./.github/workflows/reusable.yaml
    with:
      name: "I am Ihor"
    secrets:
      access-token: ${{ secrets.GITHUB_TOKEN }}

  calling-reusable-wf-of-tutor:
    uses: github-actions-course/workflows/.github/workflows/reusable.yaml@37d9ff792b46d57712294a74a8d8590a6f75b10f
    with:
      name: "Hi!"
    secrets:
      access-token: ${{ secrets.ACCESS_TOKEN }}