name: Vars && Secrets
on: push

jobs:
  log-vars:
    environment: staging
    runs-on: ubuntu-latest
    env:
      BOOLEAN_SECRET: ${{ secrets.BOOLEAN_SERCET }}
      ENV_LVL_VAR: ${{ vars.ENV_LVL_VAR }}
      REPO_LVL_VAR: ${{ vars.REPO_LVL_VAR }}
    steps:
      - name: Check secret
        if: ${{ env.BOOLEAN_SECRET == 'true' }}
        run: echo "${{ secrets.BOOLEAN_SERCET }} == 'true'"
      - name: Log vars
        run: |
          echo ${{ secrets.BOOLEAN_SERCET }}
          echo ${{ vars.ENV_LVL_VAR }}
          echo ${{ vars.REPO_LVL_VAR }}
          echo "BOOLEAN_SECRET: $BOOLEAN_SECRET"
          echo "ENV_LVL_VAR: $ENV_LVL_VAR"
          echo "REPO_LVL_VAR: $REPO_LVL_VAR"