name: Very first workflow
on: [push]

jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: echo string
              run: echo "Hi there!"
            - name: Multiline commands
              run: |
                node -v
                npm -v
