name: Working dirs & shells
on: [push]
defaults:
  run:
    shell: bash
    # working-directory: /var/lib/

jobs:
  display-wf-info:
    runs-on: ubuntu-latest
    steps:
      - name: Disolay working dir and list files
        run: |
          pwd
          ls -la
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE

      - name: Chank working dir
        working-directory: /home/runner
        run: pwd

  display-wf-info-windows:
    runs-on: windows-latest
    steps:
      - name: Disolay working dir and list files
        shell: pwsh
        run: |
          Get-Location
          dir
          echo $env:GITHUB_SHA
          echo $env:GITHUB_REPOSITORY
          echo $env:GITHUB_WORKSPACE

      - name: Python shell
        shell: python
        run: |
          print('-' * 128)
