name: Random joke
author: Grigoryan-not-available
description: "Generate random joke and send it to telegram"
inputs:
  chat_id:
    description: "Telegram bot chat id"
    required: true
  token:
    description: "Telegram bot token"
    required: true
  upload_joke:
    description: "Upload joke as an artifact?"

outputs:
  joke:
    description: "Generated joke"
    value: ${{ steps.joke.outputs.random_joke }}

runs:
  using: composite
  steps:
    # - name: Install curl
    #   shell: bash
    #   run: |
    #     apt-get -y update
    #     apt-get -y install curl
    - name: Generate joke
      shell: bash
      id: joke
      run: |
        RANDOM_JOKE_JSON=$(curl -s https://official-joke-api.appspot.com/random_joke)
        JOKE_SETUP=$(echo ${RANDOM_JOKE_JSON} | jq -r .setup)
        JOKE_PUNCHLINE="||$(echo ${RANDOM_JOKE_JSON} | jq -r .punchline)||"
        {
          echo 'random_joke<<EOF'
          echo "${JOKE_SETUP}
          ${JOKE_PUNCHLINE}"
          echo ""
          echo EOF
        } >> "$GITHUB_OUTPUT"
    - name: Generate joke file
      if: ${{ inputs.upload_joke }}
      shell: bash
      id: joke-atrifact
      run: echo "${{ steps.joke.outputs.random_joke }}" >> joke.txt
    - name: Upload joke as an atrifact
      if: ${{ inputs.upload_joke }}
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32
      with:
        name: joke
        path: joke.txt
    - name: Send joke to telegram"
      shell: bash
      run: curl -s --data-urlencode "text=${{ steps.joke.outputs.random_joke }}" https://api.telegram.org/bot${{ inputs.token }}/sendMessage?chat_id=${{ inputs.chat_id }}/&parse_mode=MarkdownV2
    